DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS trips CASCADE;
DROP TABLE IF EXISTS friendship CASCADE;
DROP TABLE IF EXISTS trip_user CASCADE;
DROP TABLE IF EXISTS user_gear CASCADE;
DROP TABLE IF EXISTS gear_checklist CASCADE;
DROP TABLE IF EXISTS user_checklist CASCADE;
-- DROP TABLE IF EXISTS day_hiking_checklist CASCADE;
-- DROP TABLE IF EXISTS backpacking_checklist CASCADE;
-- DROP TABLE IF EXISTS car_camping_checklist CASCADE;


CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  user_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  avatar TEXT NOT NULL
);


CREATE TABLE trips (
  id SERIAL PRIMARY KEY NOT NULL,
  creator_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  activity VARCHAR(255) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  latitude DOUBLE PRECISION NOT NULL
);

CREATE TABLE friendship (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id1 INTEGER REFERENCES users(id) ON DELETE CASCADE,
  user_id2 INTEGER REFERENCES users(id) ON DELETE CASCADE
);


CREATE TABLE trip_user (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  trip_id INTEGER REFERENCES trips(id) ON DELETE CASCADE
);



CREATE TABLE user_gear (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255),
  category VARCHAR(255),
  type VARCHAR(255),
  colour VARCHAR(255),
  activity VARCHAR(255)
);

CREATE TABLE gear_checklist (
  id SERIAL PRIMARY KEY NOT NULL,
  type VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  activity VARCHAR(255) NOT NULL
);

CREATE TABLE user_checklist (
  id SERIAL PRIMARY KEY NOT NULL,
  trip_id INTEGER REFERENCES trips(id) ON DELETE CASCADE,
  type_id INTEGER REFERENCES gear_checklist(id) ON DELETE CASCADE,
  checked boolean NOT NULL DEFAULT FALSE 
);

-- CREATE TABLE day_hiking_checklist (
--   id SERIAL PRIMARY KEY NOT NULL,
--   type VARCHAR(255) NOT NULL,
--   category VARCHAR(255) NOT NULL
-- );

-- CREATE TABLE backpacking_checklist (
--   id SERIAL PRIMARY KEY NOT NULL,
--   type VARCHAR(255) NOT NULL,
--   category VARCHAR(255) NOT NULL
-- );

-- CREATE TABLE car_camping_checklist (
--   id SERIAL PRIMARY KEY NOT NULL,
--   type VARCHAR(255) NOT NULL,
--   category VARCHAR(255) NOT NULL
-- );