INSERT INTO users (user_name, email, password, avatar) values ('Alec', 'alec@gmail.com', '12345', 'https://i.imgur.com/3tVgsra.jpg'); 
INSERT INTO users (user_name, email, password, avatar) values ('Cohana', 'cohana@gmail.com', '12345', 'https://i.imgur.com/FK8V841.jpg'); 
INSERT INTO users (user_name, email, password, avatar) values ('Susan', 'susan@gmail.com', '12345', 'https://i.imgur.com/TdOAdde.jpg'); 
INSERT INTO users (user_name, email, password, avatar) values ('Viktor', 'viktor@gmail.com', '12345', 'https://i.imgur.com/iHq8K8Z.jpg'); 
INSERT INTO users (user_name, email, password, avatar) values ('Sven', 'sven@gmail.com', '12345', 'https://i.imgur.com/twYrpay.jpg'); 

INSERT INTO friendship (user_id1, user_id2) VALUES (1, 2);
INSERT INTO friendship (user_id1, user_id2) VALUES (1, 3);
INSERT INTO friendship (user_id1, user_id2) VALUES (1, 4);
INSERT INTO friendship (user_id1, user_id2) VALUES (1, 5);
INSERT INTO friendship (user_id1, user_id2) VALUES (2, 3);
INSERT INTO friendship (user_id1, user_id2) VALUES (2, 4);
INSERT INTO friendship (user_id1, user_id2) VALUES (2, 5);


INSERT INTO gear_checklist (type, category, activity) VALUES ('Daypack', 'Essential Gear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Trekking poles', 'Essential Gear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Moisture-wicking underwear', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Moisture-wicking T-shirt', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Quick-drying pants/shorts', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Long-sleeve shirt', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lightweight fleece or jacket', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Boots or shoes', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Socks', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Extra clothes', 'Clothing & Footwear','hiking');

INSERT INTO gear_checklist (type, category, activity) VALUES ('Rainwear', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Long underwear', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Warm, insulated jacket or vest', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Fleece pants', 'Clothing & Footwear','hiking');

INSERT INTO gear_checklist (type, category, activity) VALUES ('Gloves or mittens', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Warm hat', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Bandana or Buff', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Gaiters', 'Clothing & Footwear','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Water bottles', 'Food & Water','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Water filter/purifier or chemical treatment', 'Food & Water','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Trail snacks', 'Food & Water','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lunch', 'Food & Water','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Extra days supply of food', 'Food & Water','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Map', 'Navigation','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Compass', 'Navigation','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Route description or guidebook', 'Navigation','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Altimeter watch', 'Navigation','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('GPS', 'Navigation','hiking');

INSERT INTO gear_checklist (type, category, activity) VALUES ('Satellite messenger/personal locator beacon', 'Navigation','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('First-aid kit or first-aid supplies', 'Emergency & First Aid','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lighter/matches and firestarter', 'Emergency & First Aid','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Emergency shelter', 'Emergency & First Aid','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Whistle', 'Emergency & First Aid','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Two itineraries: 1 left with friend + 1 under car seat', 'Emergency & First Aid','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Hand sanitizer', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Menstrual products', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Prescription medications', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Prescription glasses', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sunscreen', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sunglasses (+ sunglasses straps)', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sun hat', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('SPF-rated lip balm', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Insect repellent', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Toilet paper', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Urinary products', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sanitation trowel', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Baby wipes', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Alcohol or antiseptic wipes', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Blister treatments', 'Health & Hygiene','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Knife or multi-tool', 'Tools & Repair Items','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Small gear-repair kit', 'Tools & Repair Items','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Headlamp or flashlight', 'Hiking Extras','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camera', 'Hiking Extras','Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Interpretive field guide(s)', 'Hiking Extras','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Outdoor journal with pen/pencil', 'Hiking Extras','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Binoculars', 'Hiking Extras','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Two-way radios', 'Hiking Extras','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Credit card and/or cash', 'Personal Items','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('ID', 'Personal Items','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cellphone', 'Personal Items','hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Car keys', 'Personal Items','hiking');


INSERT INTO gear_checklist (type, category, activity) VALUES ('Camp chairs', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camp table', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lantern', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sleeping bags', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sleeping pads', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camping pillow', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Headlamps or flashlights (and extra batteries)', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sunshade, tarp or screen house', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Hammock', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cots', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sleeping bag liners', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Firewood sourced near campsite', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camp rug', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Tablecloth and clips (or tape)', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Clothesline with clips', 'Campsite','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Extra cord', 'Tools & Repair Items','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Tent-pole repair sleeve', 'Tools & Repair Items','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Pad/Mattress repair kit', 'Tools & Repair Items','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Multi-tool', 'Tools & Repair Items','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Duct tape', 'Tools & Repair Items','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Mallet or hammer (for hammering tent stakes)', 'Tools & Repair Items','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Saw or axe (for cutting firewood)', 'Tools & Repair Items','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Small broom and dustpan', 'Tools & Repair Items','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cook pots (and pot holder)', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Frying pan', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cooking utensils', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Bottle opener, can opener, corkscrew', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sharp knife', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Plates/bowls', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cutting board', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cooler', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Ice or ice substitutes', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Water bottles', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camp sink or wash bins', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Pot scrubber/sponge(s)', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Trash/recycling bags', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Dish towel', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camp grill and fuel', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Grill rack', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Griddle', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Dutch oven', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Charcoal', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Stove and fuel', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Matches/light/firestarter', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Eating utensils', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Mugs/cups', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Biodegradable soap', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Portable coffee/tea maker', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Rolling ice cream maker', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Marshmallow/hot dog roasting forks', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Small food-storage containers/bags/foil', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Large water jugs', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Large, clear plastic bins to store kitchen gear', 'Kitchen','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Solar and portable power', 'Campsite Extras','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Binoculars', 'Campsite Extras','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Navigation tools', 'Campsite Extras','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Field guides (flowers, insects)', 'Campsite Extras','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Star chart/night-sky identifier', 'Campsite Extras','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Book/reading material', 'Campsite Extras','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Notebook and pen/pencil', 'Campsite Extras','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Music player with headphones', 'Campsite Extras','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Games and toys', 'Campsite Extras','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Dog gear', 'Campsite Extras','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Dry bags, stuff sacks or clear plastic bins to store items', 'Campsite Extras','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Moisture-wicking underwear', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Moisture-wicking T-shirts', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Quick-drying pants/shorts', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Long-sleeve shirts (for sun, bugs)', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lightweight fleece or jacket', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Boots or shoes suited to terrain', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Socks (synthetic or wool)', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sleepwear', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Additional items for rainy and/or cold weather:', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Rainwear (jacket and pants)', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Long underwear', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Warm insulated jacket or vest', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Fleece pants', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Gloves or mittens', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Warm hat', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Bandanas', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Swimsuits', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Water sandals', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('In-camp sandals or booties', 'Clothing & Footwear','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Insect repellent device', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Alcohol or antiseptic wipes', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Mirror', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Brush/comb', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cosmetics', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Spare eyeglasses/contact lens supplies', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Eyeshades', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Earplugs', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Portable camp shower', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Toilet paper', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Hand sanitizer', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Toothbrush and toothpaste', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Toiletry kit', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Quick-dry towel', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Menstrual products', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Prescription medications', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('First-aid kit or first-aid supplies (see First-Aid Checklist)', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sunglasses (and sunglasses straps)', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sun hat', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lip balm', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Insect repellent', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Urinary products', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sanitation trowel (if no toilets)', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Baby wipes', 'Health & Hygiene','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Credit card and/or cash', 'Personal Items','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('ID', 'Personal Items','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cellphone', 'Personal Items','camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Campsite reservation confirmation (if required)*', 'Personal Items','camping');


INSERT INTO gear_checklist (type, category, activity) VALUES ('Backpack', 'Essential Gear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Backpacking tent', 'Essential Gear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sleeping bag', 'Essential Gear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sleeping pad', 'Essential Gear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Headlamp or flashlight', 'Essential Gear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Trekking poles', 'Essential Gear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Packable lantern', 'Essential Gear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Tent footprint', 'Essential Gear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Pillow', 'Essential Gear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Bear spray', 'Essential Gear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Backpacking stove', 'Backcountry Kitchen','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Fuel', 'Backcountry Kitchen','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cookset', 'Backcountry Kitchen','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Dishes/bowls', 'Backcountry Kitchen','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Eating Utensils', 'Backcountry Kitchen','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Mug/cup', 'Backcountry Kitchen','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Biodegradable soap', 'Backcountry Kitchen','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Small quick-dry towel', 'Backcountry Kitchen','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Collapsible water container', 'Backcountry Kitchen','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Bear canister/food sack; or hang bag + 50" nylon cord', 'Backcountry Kitchen','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Water bottles and/or reservoir ', 'Food & Water','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Water filter/purifier or chemical treatment ', 'Food & Water','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Meals', 'Food & Water','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Energy food and drinks', 'Food & Water','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Extra days supply of food ', 'Food & Water','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Moisture-wicking underwear', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Moisture-wicking T-shirt', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Quick-drying pants/shorts', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Long-sleeve shirt (for sun, bugs)', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lightweight fleece or jacket', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Boots or shoes suited to terrain', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Socks (synthetic or wool)', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Extra clothes  (beyond the minimum expectation)', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Rainwear (jacket and pants)', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Long underwear', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Warm, insulated jacket or vest', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Fleece pants', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Gloves or mittens', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Warm hat', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Bandana or Buff', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Gaiters (for rainy, snowy or muddy conditions)', 'Clothing & Footwear','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Map  (preferably inside a waterproof sleeve)', 'Navigation','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Compass ', 'Navigation','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Route description or guidebook', 'Navigation','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Watch', 'Navigation','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('GPS ', 'Navigation','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Satellite messenger/personal locator beacon ', 'Navigation','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Fire starter (for emergency survival fire) ', 'Emergency & First Aid','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('First-aid kit or first-aid supplies  (see First-Aid Checklist)', 'Emergency & First Aid','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Whistle', 'Emergency & First Aid','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lighter/matches (in waterproof container) ', 'Emergency & First Aid','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Emergency shelter ', 'Emergency & First Aid','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Two itineraries: 1 left with friend + 1 under car seat', 'Emergency & First Aid','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Toothbrush and toothpaste', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sanitation trowel', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('sealable bag (to pack it out)', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Hand sanitizer', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Toilet paper/wipes', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Menstrual products', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Prescription medications', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Prescription glasses', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sunglasses  (+ sunglass straps)', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sunscreen', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('SPF-rated lip balm ', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sun hat ', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Insect repellent ', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Urinary products', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Additional blister treatment supplies', 'Health & Hygiene','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Duct tape strips', 'Tools & Repair Items','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Knife or Multi-tool ', 'Tools & Repair Items','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Repair kit (include mattress/stove supplies) ', 'Tools & Repair Items','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Daypack (for day trips away from camp)', 'Backpacking Extras','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Star chart/night-sky identifier', 'Backpacking Extras','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Book/reading material', 'Backpacking Extras','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cards or games', 'Backpacking Extras','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camera or action cam (with extra memory cards)', 'Backpacking Extras','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Compact binoculars', 'Backpacking Extras','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Interpretive field guide(s)', 'Backpacking Extras','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Two-way radios', 'Backpacking Extras','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Outdoor journal with pen/pencil', 'Backpacking Extras','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Permits (if needed)', 'Personal Items','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Credit card and/or cash', 'Personal Items','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('ID', 'Personal Items','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Car keys', 'Personal Items','backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cellphone', 'Personal Items','backpacking');

INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (1, 'Joffre Lakes', null, 'camping', '2021-11-11', '2021-11-12', -122.4762, 50.3413, '/images/Joffre_Lakes.png');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (1, 'Brunswick Mountain', null, 'hiking', '2021-11-23', '2021-11-23', -123.234719, 49.470883, '/images/Brunswick_Mountain.png');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (2, 'Heather Trail', null, 'backpacking', '2021-12-25', '2021-12-26', -120.764843, 49.099188, '/images/Heather_Trail.jpeg');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (3, 'Joffre Lake', null, 'camping', '2021-11-05', '2021-11-06', -122.4762, 50.3413, '/images/Joffre_Lakes.png');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (4, 'Brunswick Mountain', null, 'hiking', '2021-11-07', '2021-11-10', -123.234719, 49.470883, '/images/Brunswick_Mountain.png');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (5, 'Heather Trail', null, 'backpacking', '2021-11-12', '2021-11-14', -120.764843, 49.099188, '/images/Heather_Trail.jpeg'); 
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (2, 'Spanish Banks and Jericho Beach', null, 'camping', '2021-11-15', '2021-11-17', -123.19159,49.27074,'/images/Spanish_Banks_and_Jericho_Beach.jpeg');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (3, 'Dam Mountain', null, 'hiking', '2021-11-18', '2021-11-20', -123.1335577,49.3562217, '/images/Dam_Mountain.jpeg');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (4, 'Stanley Park Seawall Trail', null, 'backpacking', '2021-12-01', '2021-12-03',-123.13071,49.29772,'/images/stanley-park-seawall-trail.png'); 
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (1, 'Sunset Beach to Second Beach', null, 'camping', '2021-12-04', '2021-12-06',-123.14004,49.28102,'/images/sunset-beach-to-second-beach.jpg');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (2, 'Crown Mountain', null, 'hiking', '2021-12-08', '2021-12-10', -123.2216091,49.3376785, '/images/crown-mountain-trail.jpg');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (3, 'Stanley Park Inner Loop', null, 'backpacking', '2021-12-11', '2021-12-14', -123.14821,49.2928,'/images/stanley-park-inner-loop.jpg'); 
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (4, 'Stanley Park', null, 'camping', '2021-12-16', '2021-12-18', -113.9192897,50.9208507, '/images/stanley-park.jpg');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (1, 'Coliseum Mountain', null, 'hiking', '2021-12-19', '2021-12-21',-123.2112447, 49.3644801, '/images/Coliseum_Mountain.jpeg');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (5, 'Everett Crowley Loop', null, 'backpacking', '2021-12-25', '2021-12-26', -123.04134,49.21204,'/images/Everett_Crowley_Loop.jpg'); 
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (2, 'Cypress Provincial Park', null, 'camping', '2021-12-22', '2021-12-24',-113.9192897,50.9208507, '/images/Cypress_Provincial_Park.jpeg');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (3, 'Mount Seymour', null, 'hiking', '2021-12-27', '2021-12-29', -123.2112447,49.3989194, '/images/Mount_Seymour.jpg');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (4, 'Vancouver and Stanley Park Seawall', null, 'backpacking', '2022-01-01', '2022-01-04', -123.14222,49.27571,'/images/Vancouver_and_Stanley_Park_Seawall.jpg'); 
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (1, 'Say Nuth Khaw Yum Provincial Park', null, 'camping', '2022-01-05', '2022-01-07', -120.3728448,51.3064702, '/images/Say_Nuth_Khaw_Yum_Provincial_Park.jpeg');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (5, 'Cypress Mountain', null, 'hiking', '2022-01-08', '2022-01-10', -123.2112447,49.3989194, '/images/Cypress_Mountain.jpg');
INSERT INTO trips (creator_id, title, description, activity, start_date, end_date, longitude, latitude, image) VALUES (2, 'Second Narrows and Lions Gate Cycling Loop', null, 'backpacking', '2022-01-11', '2021-01-14', -123.10529,49.278,'/images/Second_Narrows_and_Lions_Gate_Cycling_Loop.jpeg'); 

INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Stanley Park Seawall Trail',NULL,49.29772,-123.13071,'https://photos.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMzExNTg5NjQvM2U1MDdiYWI1N2JhM2FiOGJjOTM1NmE5MWU4OWIyMjEuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJqcGVnIiwicmVzaXplIjp7IndpZHRoIjoyMDQ4LCJoZWlnaHQiOjIwNDgsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsImpwZWciOnsidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWlzZVNjYW5zIjp0cnVlLCJxdWFudGlzYXRpb25UYWJsZSI6M319fQ==');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('False Creek South Trail',null,49.27499,-123.10231,'https://cdn-assets.alltrails.com/uploads/photo/image/24202461/extra_large_11b4e40c52ad9bf6c98bd3d40babd4ac.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Sunset Beach to Second Beach',null,49.28102,-123.14004,'https://cdn-assets.alltrails.com/uploads/photo/image/20510028/extra_large_8210355fdf50323cc306aedf2ca59217.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Spanish Banks and Jericho Beach',null,49.27074,-123.19159,'https://cdn-assets.alltrails.com/uploads/photo/image/17721856/extra_large_639497eff7a5fec4fb2362e5872c7c8d.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Salish Trail to Spanish Trail',null,49.25897,-123.22235,'https://cdn-assets.alltrails.com/uploads/photo/image/11415703/extra_large_2cc4b9c50aff0581f9a9a4989d0dd878.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Devonian Harbour Park to Harbour Green Park',null,49.29329,-123.13324,'https://cdn-assets.alltrails.com/uploads/photo/image/27801611/extra_large_e9a09867d9106d070467640140b761ac.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Queen Elizabeth Park',null,49.24123,-123.11507,'https://cdn-assets.alltrails.com/uploads/photo/image/19452360/extra_large_23daf9cfbe3c808f958c688ddaed587e.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Stanley Park Inner Loop',null,49.2928,-123.14821,'https://farm8.static.flickr.com/7205/6845779860_9bd8f7f9c4.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Arbutus Greenway',null,49.2669,-123.1409,'https://cdn-assets.alltrails.com/uploads/photo/image/35591991/extra_large_794d576cc3e6d2233322b09e296d9e06.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('VanDusen Botanical Gardens',null,49.23835,-123.12919,'https://photos.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMzcwNTk0NTQvNzBlN2ZiZTZhODE2OWJhOTk3ZTJkMzk3N2RjNmM5NTEuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJqcGVnIiwicmVzaXplIjp7IndpZHRoIjoyMDQ4LCJoZWlnaHQiOjIwNDgsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsImpwZWciOnsidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWlzZVNjYW5zIjp0cnVlLCJxdWFudGlzYXRpb25UYWJsZSI6M319fQ==');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Lost Lagoon and Rose Garden Loop',null,49.30019,-123.13695,'https://cdn-assets.alltrails.com/uploads/photo/image/23905098/extra_large_ef1215502ef00af2c55b1e9a5d475df6.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Easy Canyon and West Canyon Loop Trail',null,49.27927,-123.2416,'https://photos.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMzc2OTQ2NDIvZjZlN2E0YmIyNWM3OTNmNGRmNGI4OTNjMDA4YTc3ZjAuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJqcGVnIiwicmVzaXplIjp7IndpZHRoIjoyMDQ4LCJoZWlnaHQiOjIwNDgsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsImpwZWciOnsidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWlzZVNjYW5zIjp0cnVlLCJxdWFudGlzYXRpb25UYWJsZSI6M319fQ==');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Coal Harbour Via Stanley Park Trail',null,49.27868,-123.1375,'https://cdn-assets.alltrails.com/uploads/photo/image/27801649/extra_large_421957be0182a83f386d9af8435db208.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Fraser Foreshore Park Trail',null,49.20575,-123.03205,'https://cdn-assets.alltrails.com/uploads/photo/image/25741262/extra_large_b3d646b5a9f9368fff59140fc9ad757b.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Second Narrows and Lions Gate Cycling Loop',null,49.278,-123.10529,'https://cdn-assets.alltrails.com/uploads/photo/image/20936707/extra_large_31d0b08d62eddfba1f7429eb9236eac1.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Trout Lake Loop',null,49.25596,-123.06534,'https://photos.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMzYwNDY2NTgvMTE1NzI2OWFmZGY5MGVjMTg5MmY0NjVkZDQ1YTRkNDIuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJqcGVnIiwicmVzaXplIjp7IndpZHRoIjoyMDQ4LCJoZWlnaHQiOjIwNDgsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsImpwZWciOnsidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWlzZVNjYW5zIjp0cnVlLCJxdWFudGlzYXRpb25UYWJsZSI6M319fQ==');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Everett Crowley Loop',null,49.21204,-123.04134,'https://cdn-assets.alltrails.com/uploads/photo/image/30915700/extra_large_48159e5b8781617fb4b87b285ae37966.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Avison, Seawall and Merilees Loop',null,49.31272,-123.14384,'https://cdn-assets.alltrails.com/uploads/photo/image/24004895/extra_large_ca8049ebe44092fbb29e2b70aaeb2d28.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Chinatown Neighborhood Tour',null,49.28001,-123.10518,'https://cdn-assets.alltrails.com/uploads/photo/image/13802962/extra_large_2730dc9c56ed9c73e44492b2857fee3d.jpg');
INSERT INTO recommendations (title, description, latitude, longitude, image) VALUES ('Vancouver and Stanley Park Seawall',null,49.27571,-123.14222,'https://photos.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMzEwNzM0MDEvNjAzMDY1MTAwNzA4YzcwZDZiODMyMTQ5N2Q0ZDIyNjQuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJqcGVnIiwicmVzaXplIjp7IndpZHRoIjoyMDQ4LCJoZWlnaHQiOjIwNDgsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsImpwZWciOnsidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWlzZVNjYW5zIjp0cnVlLCJxdWFudGlzYXRpb25UYWJsZSI6M319fQ==');

