INSERT INTO users (user_name, email, password, avatar) values ('Alec', 'alec@gmail.com', '12345', 'https://i.imgur.com/3tVgsra.jpg'); 
INSERT INTO users (user_name, email, password, avatar) values ('Cohana', 'cohana@gmail.com', '12345', 'https://i.imgur.com/FK8V841.jpg'); 
INSERT INTO users (user_name, email, password, avatar) values ('Susan', 'susan@gmail.com', '12345', 'https://i.imgur.com/TdOAdde.jpg'); 
INSERT INTO users (user_name, email, password, avatar) values ('Viktor', 'viktor@gmail.com', '12345', 'https://i.imgur.com/iHq8K8Z.jpg'); 
INSERT INTO users (user_name, email, password, avatar) values ('Sven', 'sven@gmail.com', '12345', 'https://i.imgur.com/twYrpay.jpg'); 

INSERT INTO relations (user_id1, user_id2) VALUES (1, 2);
INSERT INTO relations (user_id1, user_id2) VALUES (1, 3);
INSERT INTO relations (user_id1, user_id2) VALUES (1, 4);
INSERT INTO relations (user_id1, user_id2) VALUES (1, 5);

INSERT INTO day_hiking_checklist (type, category) VALUES ('Daypack', 'Hiking Gear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Trekking poles', 'Hiking Gear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Moisture-wicking underwear', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Moisture-wicking T-shirt', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Quick-drying pants/shorts', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Long-sleeve shirt', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Lightweight fleece or jacket', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Boots or shoes', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Socks', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Extra clothes', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Rainwear', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Long underwear', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Warm, insulated jacket or vest', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Fleece pants', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Gloves or mittens', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Warm hat', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Bandana or Buff', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Gaiters', 'Clothing & Footwear');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Water bottles', 'Food & Water');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Water filter/purifier or chemical treatment', 'Food & Water');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Trail snacks', 'Food & Water');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Lunch', 'Food & Water');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Extra days supply of food', 'Food & Water');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Map', 'Navigation');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Compass', 'Navigation');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Route description or guidebook', 'Navigation');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Altimeter watch', 'Navigation');
INSERT INTO day_hiking_checklist (type, category) VALUES ('GPS', 'Navigation');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Satellite messenger/personal locator beacon', 'Navigation');
INSERT INTO day_hiking_checklist (type, category) VALUES ('First-aid kit or first-aid supplies', 'Emergency & First Aid');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Lighter/matches and firestarter', 'Emergency & First Aid');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Emergency shelter', 'Emergency & First Aid');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Whistle', 'Emergency & First Aid');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Two itineraries: 1 left with friend + 1 under car seat', 'Emergency & First Aid');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Hand sanitizer', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Menstrual products', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Prescription medications', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Prescription glasses', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Sunscreen', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Sunglasses (+ sunglasses straps)', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Sun hat', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('SPF-rated lip balm', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Insect repellent', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Toilet paper', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Urinary products', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Sanitation trowel', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Baby wipes', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Alcohol or antiseptic wipes', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Blister treatments', 'Health & Hygiene');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Knife or multi-tool', 'Tools & Repair Items');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Small gear-repair kit', 'Tools & Repair Items');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Headlamp or flashlight', 'Day Hiking Extras');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Camera', 'Day Hiking Extras');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Interpretive field guide(s)', 'Day Hiking Extras');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Outdoor journal with pen/pencil', 'Day Hiking Extras');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Binoculars', 'Day Hiking Extras');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Two-way radios', 'Day Hiking Extras');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Credit card and/or cash', 'Personal Items');
INSERT INTO day_hiking_checklist (type, category) VALUES ('ID', 'Personal Items');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Cellphone', 'Personal Items');
INSERT INTO day_hiking_checklist (type, category) VALUES ('Car keys', 'Personal Items');

INSERT INTO car_camping_checklist (type, category) VALUES ('Camp chairs', 'Campsite');
INSERT INTO car_camping_checklist (type, category) VALUES ('Camp table', 'Campsite');
INSERT INTO car_camping_checklist (type, category) VALUES ('Lantern', 'Campsite');
INSERT INTO car_camping_checklist (type, category) VALUES ('Sunshade, tarp or screen house', 'Campsite');
INSERT INTO car_camping_checklist (type, category) VALUES ('Hammock', 'Campsite');
INSERT INTO car_camping_checklist (type, category) VALUES ('Cots', 'Campsite');
INSERT INTO car_camping_checklist (type, category) VALUES ('Sleeping bag liners', 'Campsite');
INSERT INTO car_camping_checklist (type, category) VALUES ('Firewood sourced near campsite', 'Campsite');
INSERT INTO car_camping_checklist (type, category) VALUES ('Camp rug', 'Campsite');
INSERT INTO car_camping_checklist (type, category) VALUES ('Tablecloth and clips (or tape)', 'Campsite');
INSERT INTO car_camping_checklist (type, category) VALUES ('Clothesline with clips', 'Campsite');
INSERT INTO car_camping_checklist (type, category) VALUES ('Extra cord', 'Tools & Repair Items');
INSERT INTO car_camping_checklist (type, category) VALUES ('Tent-pole repair sleeve', 'Tools & Repair Items');
INSERT INTO car_camping_checklist (type, category) VALUES ('Pad/Mattress repair kit', 'Tools & Repair Items');
INSERT INTO car_camping_checklist (type, category) VALUES ('Mallet or hammer (for hammering tent stakes)', 'Tools & Repair Items');
INSERT INTO car_camping_checklist (type, category) VALUES ('Saw or axe (for cutting firewood)', 'Tools & Repair Items');
INSERT INTO car_camping_checklist (type, category) VALUES ('Small broom and dustpan', 'Tools & Repair Items');
INSERT INTO car_camping_checklist (type, category) VALUES ('Cook pots (and pot holder)', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Frying pan', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Cooking utensils', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Bottle opener, can opener, corkscrew', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Sharp knife', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Plates/bowls', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Cutting board', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Cooler', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Ice or ice substitutes', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Water bottles', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Camp sink or wash bins', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Pot scrubber/sponge(s)', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Trash/recycling bags', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Dish towel', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Camp grill and fuel', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Grill rack', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Griddle', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Dutch oven', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Charcoal', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Portable coffee/tea maker', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Rolling ice cream maker', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Marshmallow/hot dog roasting forks', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Small food-storage containers/bags/foil', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Large water jugs', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Large, clear plastic bins to store kitchen gear', 'Kitchen');
INSERT INTO car_camping_checklist (type, category) VALUES ('Solar and portable power', 'Campsite Extras');
INSERT INTO car_camping_checklist (type, category) VALUES ('Star chart/night-sky identifier', 'Campsite Extras');
INSERT INTO car_camping_checklist (type, category) VALUES ('Book/reading material', 'Campsite Extras');
INSERT INTO car_camping_checklist (type, category) VALUES ('Notebook and pen/pencil', 'Campsite Extras');
INSERT INTO car_camping_checklist (type, category) VALUES ('Music player with headphones', 'Campsite Extras');
INSERT INTO car_camping_checklist (type, category) VALUES ('Games and toys', 'Campsite Extras');
INSERT INTO car_camping_checklist (type, category) VALUES ('Dog gear', 'Campsite Extras');
INSERT INTO car_camping_checklist (type, category) VALUES ('Dry bags, stuff sacks or clear plastic bins to store items', 'Campsite Extras');
INSERT INTO car_camping_checklist (type, category) VALUES ('Swimsuits', 'Clothing & Footwear');
INSERT INTO car_camping_checklist (type, category) VALUES ('Water sandals', 'Clothing & Footwear');
INSERT INTO car_camping_checklist (type, category) VALUES ('In-camp sandals or booties', 'Clothing & Footwear');
INSERT INTO car_camping_checklist (type, category) VALUES ('Insect repellent device', 'Health & Hygiene');
INSERT INTO car_camping_checklist (type, category) VALUES ('Alcohol or antiseptic wipes', 'Health & Hygiene');
INSERT INTO car_camping_checklist (type, category) VALUES ('Mirror', 'Health & Hygiene');
INSERT INTO car_camping_checklist (type, category) VALUES ('Brush/comb', 'Health & Hygiene');
INSERT INTO car_camping_checklist (type, category) VALUES ('Cosmetics', 'Health & Hygiene');
INSERT INTO car_camping_checklist (type, category) VALUES ('Spare eyeglasses/contact lens supplies', 'Health & Hygiene');
INSERT INTO car_camping_checklist (type, category) VALUES ('Eyeshades', 'Health & Hygiene');
INSERT INTO car_camping_checklist (type, category) VALUES ('Earplugs', 'Health & Hygiene');
INSERT INTO car_camping_checklist (type, category) VALUES ('Portable camp shower', 'Health & Hygiene');

INSERT INTO backpacking_checklist (type, category) VALUES ('Backpack', 'Backpacking Gear');
INSERT INTO backpacking_checklist (type, category) VALUES ('Backpacking tent', 'Backpacking Gear');
INSERT INTO backpacking_checklist (type, category) VALUES ('Sleeping bag', 'Backpacking Gear');
INSERT INTO backpacking_checklist (type, category) VALUES ('Packable lantern', 'Backpacking Gear');
INSERT INTO backpacking_checklist (type, category) VALUES ('Tent footprint', 'Backpacking Gear');
INSERT INTO backpacking_checklist (type, category) VALUES ('Pillow', 'Backpacking Gear');
INSERT INTO backpacking_checklist (type, category) VALUES ('Bear spray', 'Backpacking Gear');
INSERT INTO backpacking_checklist (type, category) VALUES ('Backpacking stove', 'Backcountry Kitchen');
INSERT INTO backpacking_checklist (type, category) VALUES ('Fuel', 'Backcountry Kitchen');
INSERT INTO backpacking_checklist (type, category) VALUES ('Cookset', 'Backcountry Kitchen');
INSERT INTO backpacking_checklist (type, category) VALUES ('Dishes/bowls', 'Backcountry Kitchen');
INSERT INTO backpacking_checklist (type, category) VALUES ('Eating Utensils', 'Backcountry Kitchen');
INSERT INTO backpacking_checklist (type, category) VALUES ('Mug/cup', 'Backcountry Kitchen');
INSERT INTO backpacking_checklist (type, category) VALUES ('Biodegradable soap', 'Backcountry Kitchen');
INSERT INTO backpacking_checklist (type, category) VALUES ('Small quick-dry towel', 'Backcountry Kitchen');
INSERT INTO backpacking_checklist (type, category) VALUES ('Collapsible water container', 'Backcountry Kitchen');
INSERT INTO backpacking_checklist (type, category) VALUES ('Bear canister/food sack; or hang bag + 50" nylon cord', 'Backcountry Kitchen');
INSERT INTO backpacking_checklist (type, category) VALUES ('Water bottles and/or reservoir *', 'Food & Water');
INSERT INTO backpacking_checklist (type, category) VALUES ('Water filter/purifier or chemical treatment *', 'Food & Water');
INSERT INTO backpacking_checklist (type, category) VALUES ('Meals', 'Food & Water');
INSERT INTO backpacking_checklist (type, category) VALUES ('Energy food and drinks', 'Food & Water');
INSERT INTO backpacking_checklist (type, category) VALUES ('Fire starter (for emergency survival fire) *', 'Emergency & First Aid');
INSERT INTO backpacking_checklist (type, category) VALUES ('Toothbrush and toothpaste', 'Health & Hygiene');
INSERT INTO backpacking_checklist (type, category) VALUES ('Sanitation trowel', 'Health & Hygiene');
INSERT INTO backpacking_checklist (type, category) VALUES ('sealable bag (to pack it out)', 'Health & Hygiene');
INSERT INTO backpacking_checklist (type, category) VALUES ('Duct tape strips', 'Tools & Repair Items');
INSERT INTO backpacking_checklist (type, category) VALUES ('Daypack (for day trips away from camp)', 'Backpacking Extras');
INSERT INTO backpacking_checklist (type, category) VALUES ('Star chart/night-sky identifier', 'Backpacking Extras');
INSERT INTO backpacking_checklist (type, category) VALUES ('Book/reading material', 'Backpacking Extras');
INSERT INTO backpacking_checklist (type, category) VALUES ('Cards or games', 'Backpacking Extras');
INSERT INTO backpacking_checklist (type, category) VALUES ('Permits (if needed)', 'Personal Items');
