INSERT INTO users (user_name, email, password, avatar) values ('Alec', 'alec@gmail.com', '12345', 'https://i.imgur.com/3tVgsra.jpg'); 
INSERT INTO users (user_name, email, password, avatar) values ('Cohana', 'cohana@gmail.com', '12345', 'https://i.imgur.com/FK8V841.jpg'); 
INSERT INTO users (user_name, email, password, avatar) values ('Susan', 'susan@gmail.com', '12345', 'https://i.imgur.com/TdOAdde.jpg'); 
INSERT INTO users (user_name, email, password, avatar) values ('Viktor', 'viktor@gmail.com', '12345', 'https://i.imgur.com/iHq8K8Z.jpg'); 
INSERT INTO users (user_name, email, password, avatar) values ('Sven', 'sven@gmail.com', '12345', 'https://i.imgur.com/twYrpay.jpg'); 

INSERT INTO friendship (user_id1, user_id2) VALUES (1, 2);
INSERT INTO friendship (user_id1, user_id2) VALUES (1, 3);
INSERT INTO friendship (user_id1, user_id2) VALUES (1, 4);
INSERT INTO friendship (user_id1, user_id2) VALUES (1, 5);
INSERT INTO friendship (user_id1, user_id2) VALUES (2, 1);
INSERT INTO friendship (user_id1, user_id2) VALUES (2, 3);
INSERT INTO friendship (user_id1, user_id2) VALUES (2, 4);
INSERT INTO friendship (user_id1, user_id2) VALUES (2, 5);

INSERT INTO gear_checklist (type, category, activity) VALUES ('Daypack', 'Essential Gear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Trekking poles', 'Essential Gear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Moisture-wicking underwear', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Moisture-wicking T-shirt', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Quick-drying pants/shorts', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Long-sleeve shirt', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lightweight fleece or jacket', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Boots or shoes', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Socks', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Extra clothes', 'Clothing & Footwear','Day Hiking');

INSERT INTO gear_checklist (type, category, activity) VALUES ('Rainwear', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Long underwear', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Warm, insulated jacket or vest', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Fleece pants', 'Clothing & Footwear','Day Hiking');

INSERT INTO gear_checklist (type, category, activity) VALUES ('Gloves or mittens', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Warm hat', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Bandana or Buff', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Gaiters', 'Clothing & Footwear','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Water bottles', 'Food & Water','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Water filter/purifier or chemical treatment', 'Food & Water','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Trail snacks', 'Food & Water','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lunch', 'Food & Water','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Extra days supply of food', 'Food & Water','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Map', 'Navigation','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Compass', 'Navigation','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Route description or guidebook', 'Navigation','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Altimeter watch', 'Navigation','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('GPS', 'Navigation','Day Hiking');

INSERT INTO gear_checklist (type, category, activity) VALUES ('Satellite messenger/personal locator beacon', 'Navigation','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('First-aid kit or first-aid supplies', 'Emergency & First Aid','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lighter/matches and firestarter', 'Emergency & First Aid','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Emergency shelter', 'Emergency & First Aid','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Whistle', 'Emergency & First Aid','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Two itineraries: 1 left with friend + 1 under car seat', 'Emergency & First Aid','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Hand sanitizer', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Menstrual products', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Prescription medications', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Prescription glasses', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sunscreen', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sunglasses (+ sunglasses straps)', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sun hat', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('SPF-rated lip balm', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Insect repellent', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Toilet paper', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Urinary products', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sanitation trowel', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Baby wipes', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Alcohol or antiseptic wipes', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Blister treatments', 'Health & Hygiene','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Knife or multi-tool', 'Tools & Repair Items','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Small gear-repair kit', 'Tools & Repair Items','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Headlamp or flashlight', 'Day Hiking Extras','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camera', 'Day Hiking Extras','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Interpretive field guide(s)', 'Day Hiking Extras','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Outdoor journal with pen/pencil', 'Day Hiking Extras','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Binoculars', 'Day Hiking Extras','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Two-way radios', 'Day Hiking Extras','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Credit card and/or cash', 'Personal Items','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('ID', 'Personal Items','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cellphone', 'Personal Items','Day Hiking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Car keys', 'Personal Items','Day Hiking');




INSERT INTO gear_checklist (type, category, activity) VALUES ('Camp chairs', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camp table', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lantern', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sleeping bags', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sleeping pads', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camping pillow', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Headlamps or flashlights (and extra batteries)', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sunshade, tarp or screen house', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Hammock', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cots', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sleeping bag liners', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Firewood sourced near campsite', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camp rug', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Tablecloth and clips (or tape)', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Clothesline with clips', 'Campsite','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Extra cord', 'Tools & Repair Items','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Tent-pole repair sleeve', 'Tools & Repair Items','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Pad/Mattress repair kit', 'Tools & Repair Items','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Multi-tool', 'Tools & Repair Items','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Duct tape', 'Tools & Repair Items','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Mallet or hammer (for hammering tent stakes)', 'Tools & Repair Items','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Saw or axe (for cutting firewood)', 'Tools & Repair Items','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Small broom and dustpan', 'Tools & Repair Items','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cook pots (and pot holder)', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Frying pan', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cooking utensils', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Bottle opener, can opener, corkscrew', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sharp knife', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Plates/bowls', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cutting board', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cooler', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Ice or ice substitutes', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Water bottles', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camp sink or wash bins', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Pot scrubber/sponge(s)', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Trash/recycling bags', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Dish towel', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camp grill and fuel', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Grill rack', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Griddle', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Dutch oven', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Charcoal', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Stove and fuel', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Matches/light/firestarter', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Eating utensils', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Mugs/cups', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Biodegradable soap', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Portable coffee/tea maker', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Rolling ice cream maker', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Marshmallow/hot dog roasting forks', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Small food-storage containers/bags/foil', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Large water jugs', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Large, clear plastic bins to store kitchen gear', 'Kitchen','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Solar and portable power', 'Campsite Extras','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Binoculars', 'Campsite Extras','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Navigation tools', 'Campsite Extras','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Field guides (flowers, insects)', 'Campsite Extras','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Star chart/night-sky identifier', 'Campsite Extras','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Book/reading material', 'Campsite Extras','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Notebook and pen/pencil', 'Campsite Extras','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Music player with headphones', 'Campsite Extras','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Games and toys', 'Campsite Extras','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Dog gear', 'Campsite Extras','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Dry bags, stuff sacks or clear plastic bins to store items', 'Campsite Extras','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Moisture-wicking underwear', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Moisture-wicking T-shirts', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Quick-drying pants/shorts', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Long-sleeve shirts (for sun, bugs)', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lightweight fleece or jacket', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Boots or shoes suited to terrain', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Socks (synthetic or wool)', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sleepwear', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Additional items for rainy and/or cold weather:', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Rainwear (jacket and pants)', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Long underwear', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Warm insulated jacket or vest', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Fleece pants', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Gloves or mittens', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Warm hat', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Bandanas', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Swimsuits', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Water sandals', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('In-camp sandals or booties', 'Clothing & Footwear','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Insect repellent device', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Alcohol or antiseptic wipes', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Mirror', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Brush/comb', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cosmetics', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Spare eyeglasses/contact lens supplies', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Eyeshades', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Earplugs', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Portable camp shower', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Toilet paper', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Hand sanitizer', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Toothbrush and toothpaste', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Toiletry kit', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Quick-dry towel', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Menstrual products', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Prescription medications', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('First-aid kit or first-aid supplies (see First-Aid Checklist)', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sunglasses (and sunglasses straps)', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sun hat', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lip balm', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Insect repellent', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Urinary products', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sanitation trowel (if no toilets)', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Baby wipes', 'Health & Hygiene','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Credit card and/or cash', 'Personal Items','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('ID', 'Personal Items','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cellphone', 'Personal Items','Car Camping');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Campsite reservation confirmation (if required)*', 'Personal Items','Car Camping');


INSERT INTO gear_checklist (type, category, activity) VALUES ('Backpack', 'Essential Gear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Backpacking tent', 'Essential Gear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sleeping bag', 'Essential Gear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sleeping pad', 'Essential Gear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Headlamp or flashlight', 'Essential Gear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Trekking poles', 'Essential Gear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Packable lantern', 'Essential Gear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Tent footprint', 'Essential Gear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Pillow', 'Essential Gear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Bear spray', 'Essential Gear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Backpacking stove', 'Backcountry Kitchen','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Fuel', 'Backcountry Kitchen','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cookset', 'Backcountry Kitchen','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Dishes/bowls', 'Backcountry Kitchen','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Eating Utensils', 'Backcountry Kitchen','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Mug/cup', 'Backcountry Kitchen','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Biodegradable soap', 'Backcountry Kitchen','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Small quick-dry towel', 'Backcountry Kitchen','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Collapsible water container', 'Backcountry Kitchen','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Bear canister/food sack; or hang bag + 50" nylon cord', 'Backcountry Kitchen','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Water bottles and/or reservoir ', 'Food & Water','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Water filter/purifier or chemical treatment ', 'Food & Water','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Meals', 'Food & Water','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Energy food and drinks', 'Food & Water','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Extra days supply of food ', 'Food & Water','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Moisture-wicking underwear', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Moisture-wicking T-shirt', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Quick-drying pants/shorts', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Long-sleeve shirt (for sun, bugs)', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lightweight fleece or jacket', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Boots or shoes suited to terrain', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Socks (synthetic or wool)', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Extra clothes  (beyond the minimum expectation)', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Rainwear (jacket and pants)', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Long underwear', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Warm, insulated jacket or vest', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Fleece pants', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Gloves or mittens', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Warm hat', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Bandana or Buff', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Gaiters (for rainy, snowy or muddy conditions)', 'Clothing & Footwear','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Map  (preferably inside a waterproof sleeve)', 'Navigation','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Compass ', 'Navigation','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Route description or guidebook', 'Navigation','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Watch', 'Navigation','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('GPS ', 'Navigation','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Satellite messenger/personal locator beacon ', 'Navigation','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Fire starter (for emergency survival fire) ', 'Emergency & First Aid','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('First-aid kit or first-aid supplies  (see First-Aid Checklist)', 'Emergency & First Aid','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Whistle', 'Emergency & First Aid','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Lighter/matches (in waterproof container) ', 'Emergency & First Aid','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Emergency shelter ', 'Emergency & First Aid','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Two itineraries: 1 left with friend + 1 under car seat', 'Emergency & First Aid','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Toothbrush and toothpaste', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sanitation trowel', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('sealable bag (to pack it out)', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Hand sanitizer', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Toilet paper/wipes', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Menstrual products', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Prescription medications', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Prescription glasses', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sunglasses  (+ sunglass straps)', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sunscreen', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('SPF-rated lip balm ', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Sun hat ', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Insect repellent ', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Urinary products', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Additional blister treatment supplies', 'Health & Hygiene','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Duct tape strips', 'Tools & Repair Items','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Knife or Multi-tool ', 'Tools & Repair Items','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Repair kit (include mattress/stove supplies) ', 'Tools & Repair Items','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Daypack (for day trips away from camp)', 'Backpacking Extras','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Star chart/night-sky identifier', 'Backpacking Extras','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Book/reading material', 'Backpacking Extras','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cards or games', 'Backpacking Extras','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Camera or action cam (with extra memory cards)', 'Backpacking Extras','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Compact binoculars', 'Backpacking Extras','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Interpretive field guide(s)', 'Backpacking Extras','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Two-way radios', 'Backpacking Extras','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Outdoor journal with pen/pencil', 'Backpacking Extras','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Permits (if needed)', 'Personal Items','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Credit card and/or cash', 'Personal Items','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('ID', 'Personal Items','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Car keys', 'Personal Items','Backpacking');
INSERT INTO gear_checklist (type, category, activity) VALUES ('Cellphone', 'Personal Items','Backpacking');
